server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: ms-parameter
        uri: lb://ms-parameter
        predicates:
          - Path=/parameter/**
      - id: ms-person
        uri: lb://ms-person
        predicates:
          - Path=/api/**
      - id: ms-client
        uri: lb://ms-client
        predicates:
          - Path=/api/**